import = ["/Users/mhennefarth/.config/alacritty/gruvbox_dark.toml"]

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
#family = "GohuFont uni14 Nerd Font Propo"
family = "SauceCodePro Nerd Font"

[window]
decorations = "Buttonless"
dynamic_title = true
option_as_alt = "Both"

[window.padding]
x = 10
y = 10
