import:
  - ~/.config/alacritty/gruvbox_dark.yml

env:
  TERM: xterm-256color

# Font Specification
font:
  normal: 
     family: GohuFont uni14 Nerd Font

  size: 14
  # For thiner fonts (which I like..)
  # defaults write org.alacritty AppleFontSmoothing -int 0

cursor:
  style:
    shape: Beam
  
  ci_mode_style:
    shape: Block

window:
  padding:
    x: 10
    y: 10
  # decorations: "Buttonless"
  # opacity: 1.0
