import:
  - ~/.config/alacritty/gruvbox_material.yml

env:
  TERM: xterm-256color

# Font Specification
font:
  normal: 
    family: DinaRemasterII
      #family: TerminessTTF Nerd Font Mono # Fall-back font for weird symbols
    style: Medium

  size: 18

cursor:
  style:
    shape: Beam
  
  ci_mode_style:
    shape: Block

window:
  padding:
    x: 10
    y: 10
  decorations: "Buttonless"
