import:
  - ~/.config/alacritty/gruvbox_dark.yml
env:
  TERM: xterm-256color
# Font Specification
font:
  # For thiner fonts (which I like..)
  # defaults write org.alacritty AppleFontSmoothing -int 0
  normal:
    family: GohuFont uni14 Nerd Font Propo
  size: 14
  offset:
    x: 1
    y: 0
  draw_bold_text_with_bright_colors: true
cursor:
  style:
    shape: Beam
  ci_mode_style:
    shape: Block
window:
  padding:
    x: 10
    y: 10
  dynamic_title: true
# decorations: "Buttonless"
# opacity: 0.95
