# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'
  selection:
    text: '0xc1c1c1'
    background: '0x413e3d'
  # Normal colors
  normal:
    black: '0x353535'
    red: '0xd73925'
    green: '0xa8a521'
    yellow: '0xdfa82a'
    blue: '0x549699'
    magenta: '0xbf7897'
    cyan: '0x79aa7d'
    white: '0xb7a996'
  # Bright colors
  bright:
    black: '0xa39586'
    red: '0xfe6142'
    green: '0xc4c431'
    yellow: '0xfcc73c'
    blue: '0x94b3a8'
    magenta: '0xdc9aab'
    cyan: '0x9dd08e'
    white: '0xefe1bf'
