#!/bin/zsh
# zsh environment file. Environmental variables are set here

# Default Programs
export EDITOR="nvim"
export BROWSER="/opt/homebrew/Caskroom/firefox/106.0.5/Firefox.app/Contents/MacOS/firefox"

# Adds ~/.local/bin to path
export PATH="$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//'):$PATH"
export PATH="$(find $HOME/.local/bin -type l -ls | rev | cut -f3 -d" " | rev| tr '\n' ':' | sed 's/:*$//'):$PATH"
export PATH=.:$PATH

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter/"
export IPYTHONDIR="${XDG_CONFIG_HOME:-$HOME/.config}/ipython/"
export MYVIMRC="${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc"
export MPLCONFIGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/matplotlib/"
export ZSH_COMPDUMP="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zsh_compdump"
export ZSH="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export LESSHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/less/lesshst"
export CPM_SOURCE_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/CPM"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/pass"
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch/default/config"
export CCACHE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ccache"

export RUSTUP_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/rustup"
export CARGO_HOME="${XDG_CACHE_HOME:-$HOME/.cache}/cargo"
