# Taps
tap "homebrew/cask-fonts"

# packages
brew "htop"
brew "neovim"
brew "tmux"
brew "clang-format"
brew "cmake"
brew "zsh-syntax-highlighting"
brew "gpg"
brew "gnuplot"
brew "virtualenv"
brew "pass"
brew "eza"
brew "rg"

# Temp for neomutt
brew "neomutt"
brew "isync"
brew "msmtp"
brew "lynx"
brew "erikw/tap/xdg-urlview"
brew "pandoc"
brew "lbdb"
brew "khard"
brew "khal"

# Applications
cask "firefox"
cask "discord"
cask "rectangle"
cask "mactex-no-gui"
cask "xquartz"
cask "spotify"
cask "cyberduck"
cask "zotero"
cask "skim"
#cask "wezterm"
cask "keepassxc"
cask "ghostty"

# I still like DinaRemasterII
# Fonts
cask "font-gohufont-nerd-font"
cask "font-computer-modern"
cask "font-iosevka-term-nerd-font"
